command:
  topics:
    command_publisher: "/robot/command"
    control_subscriber: "/robot/control"
    joystick_subscriber: "/command/joystick"
    robot_subscriber: "/command/robot"
    teensy_subscriber: "/robot/teensy"

  loop:
    period: 0.05 # s

  force:
    deadzone: 1.0 # N
    clamp_min: -3.0 # N
    clamp_max: 3.0 # N
    useful_range: 3.0 # N
    low_pass_alpha: 0.35

  linear:
    forward_gain: 25.0 # deg/s
    reverse_gain: 17.0 # deg/s
    max: 25.0 # deg/s
    min: -17.0 # deg/s
    max_acceleration: 6.0 # deg/s^2
    max_deceleration: 12.0 # deg/s^2

  angular:
    max_acceleration: 90.0 # deg/s^2
