lidar_node:
  ros__parameters:
    frame_id: "lidar"
    lidar_topic: "robot/lidar"
    imu_topic: "robot/imu"
    publish_freq: 30.0 # Hz

    xfer_format: 1
    multi_topic: 0
    data_src: 0
    output_type: 0

    range_min: 0.05 # m
    range_max: 5.0 # m
    min_z: -0.30 # m
    max_z: 1.20 # m

    scan_angle_offset: -1.5707963 # rad
    scan_angle_min: -3.1415 # rad
    scan_angle_max: 3.1416 # rad
    scan_angle_increment: 0.0087 # rad
    scan_time: 0.0333 # s
    use_inf: true
