teensy:
  topics:
    teensy_publisher: "/robot/teensy"
    state_publisher: "/robot/state"
    odometry_publisher: "/robot/odometry"
    command_subscriber: "/robot/command"

  frames:
    odometry: "odom"
    base: "base_link"

  rates:
    serial_read: 1000 # Hz
    drive_command: 100 # Hz
    handle_command: 20 # Hz

  serial:
    identifier: "VID:PID=16C0:0483"
    baudrate: 115200
    timeout: 0.01 # s
    boot_delay: 1.0 # s
    motor_setup_delay: 0.5 # s

  drive:
    left:
      p_gain: 0.0810
      i_gain: 0.8005
      d_gain: 0.0
    right:
      p_gain: 0.0810
      i_gain: 0.8005
      d_gain: 0.0

  handle:
    torque_limit: 1.0 # Nm
    pulse:
      torque: 1.0 # Nm
      hold_time: 0.05 # s
      sequence: [1.0, -1.0, 1.0, -1.0, 0.0]
    nudge:
      torque: 1.0 # Nm
      hold_time: 0.10 # s

  odometry:
    max_timestep: 1.0 # s
