#ifndef LIVOX_DRIVER_VERSION_H_
#define LIVOX_DRIVER_VERSION_H_

#define LIVOX_DRIVER_VER_MAJOR 1
#define LIVOX_DRIVER_VER_MINOR 2
#define LIVOX_DRIVER_VER_PATCH 6

#define GET_STRING(n) GET_STRING_DIRECT(n)
#define GET_STRING_DIRECT(n) #n

#define LIVOX_DRIVER_VERSION_STRING                      \
  GET_STRING(LIVOX_DRIVER_VER_MAJOR)                     \
  "." GET_STRING(LIVOX_DRIVER_VER_MINOR) "." GET_STRING( \
      LIVOX_DRIVER_VER_PATCH)

#endif
